Webgentle.Bookstore/Models/BookModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Webgentle.Bookstore.Enums;
using Webgentle.Bookstore.Helpers;

namespace Webgentle.Bookstore.Models
{
    public class BookModel
    {
        

        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter the title")]
        [StringLength(100, MinimumLength = 5)]
        public string Title { get; set; }

        [Required(ErrorMessage = "Enter the name of the Author")]
        public string Author { get; set; }

        [StringLength(250, ErrorMessage = "Description can not have more length than 250 characters.")]
        public string Description { get; set; }
        public string Category { get; set; }
       
        [Required(ErrorMessage = "Please enter Total Number of Pages")]
        [Display(Name = "Total Number of Pages")]
        public int? TotalPages { get; set; }

        [Required(ErrorMessage = "Please choose a language")]
        [Display(Name = "Language")]
        public int LanguageId { get; set; }
        public string Language { get; set; }

        [Required(ErrorMessage = "Please choose your languages")]
        public LanguageEnum LanguageEnum  { get; set; }

        [Display(Name = "Choose the cover photo of your book")]
        [Required]
        public IFormFile CoverPhoto { get; set;}
        public string CoverImagePath { get; set; }

        [Display(Name = "Choose the gallery images of your book")]
        [Required]
        public IFormFileCollection GalleryFiles { get; set; }
        public List<GalleryModel> Gallery { get; set; }
        public int MyProperty { get; set; }

        [Display(Name = "Choose the pdf file of your book")]
        public IFormFile PdfFile { get; set; }
        public string PdfUrl { get; set; }

    }
}

Webgentle.Bookstore/Models/GalleryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Webgentle.Bookstore.Models
{
    public class GalleryModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
    }
}

Webgentle.Bookstore/Models/LanguageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Webgentle.Bookstore.Models
{
    public class LanguageModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

Webgentle.Bookstore/Components/TopBooksViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Webgentle.Bookstore.Repository;

namespace Webgentle.Bookstore.Components
{
    public class TopBooksViewComponent : ViewComponent
    {
        private BookRepository _bookRepository;

        public TopBooksViewComponent(BookRepository bookRepository )
        {
            _bookRepository = bookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var data = await _bookRepository.GetTopBooksAsync(count);

            return View(data);
        }
    }
}

Webgentle.Bookstore/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Webgentle.Bookstore.Models;
using Webgentle.Bookstore.Repository;

namespace Webgentle.Bookstore.Controllers
{
    public class BookController : Controller
    {
        private readonly BookRepository _bookrepository = null;
        private readonly LanguageRepository _languageRepository = null;
        private readonly IWebHostEnvironment _webHostEnvironment;

        [ViewData]
        public string Title { get; set; }

        public BookController(BookRepository bookRepository, LanguageRepository languageRepository, IWebHostEnvironment webHostEnvironment)
        {
             _bookrepository = bookRepository;
            _languageRepository = languageRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<ViewResult>  GetAllBooks()
        {
            Title = "Books";

            var data =await  _bookrepository.GetAllBooks();
            return View(data);
        }

        [Route("book-details/{id}", Name = "bookDetailsRoute")]
        public async Task<ViewResult> GetBook(int id)
        {
            
            var data = await _bookrepository.GetBookById(id);

            return View(data);
        }

        public List<BookModel> FindBooks(string bookName, string authName)
        {
            return _bookrepository.SearchBook(bookName, authName);
        }

        public async Task<ViewResult> AddNewBookAsync(bool isSuccess = false, int bookId = 0)
        {

            var model = new BookModel();

            ViewBag.Language = new SelectList(await _languageRepository.GetLanguages(), "Id", "Name");

            ViewBag.IsSuccess = isSuccess;
            ViewBag.BookId = bookId;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddNewBook(BookModel bookModel)
        {
            if(ModelState.IsValid)
            {
                if(bookModel.CoverPhoto != null)
                {
                    string folder = "books/cover/";
                    bookModel.CoverImagePath = await UploadFile(bookModel.CoverPhoto, folder);
                }

                if(bookModel.GalleryFiles != null)
                {
                    string folder = "books/gallery/";

                    bookModel.Gallery = new List<GalleryModel>();
                    foreach(var file in bookModel.GalleryFiles)
                    {
                        var gallery = new GalleryModel()
                        {
                            Name = file.FileName,
                            URL = await UploadFile(file, folder)
                        };

                        bookModel.Gallery.Add(gallery);
                    }

                    
                }

                if (bookModel.PdfFile != null)
                {
                    string folder = "books/pdffile/";
                    bookModel.PdfUrl = await UploadFile(bookModel.PdfFile, folder);
                }

                int id = await _bookrepository.AddNewBook(bookModel);

                if (id > 0)
                {
                    return RedirectToAction(nameof(AddNewBook), new { isSuccess = true, bookId = id });
                }

                

            }

            ViewBag.Language = new SelectList(await _languageRepository.GetLanguages(), "Id", "Name");





            return View();

        }

        private async Task<string> UploadFile(IFormFile image, string folder)
        {
            folder += Guid.NewGuid().ToString() + "_" + image.FileName;
            var serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, folder);

            string imagePath = "/" + folder;

            await image.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
            return imagePath;
        }

        private async Task<List<LanguageModel>> GetLanguages()
        {
            return await _languageRepository.GetLanguages();
        }
    }
}

Webgentle.Bookstore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Dynamic;
using Webgentle.Bookstore.Models;

namespace Webgentle.Bookstore.Controllers
{
    public class HomeController : Controller
    {
        [ViewData]
        public string Title { get; set; }

        [ViewData]
        public BookModel book1 { get; set; }

        public ViewResult Index()
        {
            Title = "Home";

            book1 = new BookModel() { Id = 10, Title = "hello", Author = "Vivek", Category = "Nothing" };
            return View();
        }

        public ViewResult AboutUs()
        {
            Title = "AboutUs";
            return View();
        }

        public ViewResult ContactUs()
        {
            Title = "ContactUs";

            return View();
        }
    }
}

Webgentle.Bookstore/Views/Book/AddNewBook.cshtml
@model BookModel
@using Webgentle.Bookstore.Enums

@{
    ViewData["Title"] = "Add New Book";

}
<div class="container">
    <h3 class=display-4>Add New Book</h3>
    <hr />
    @if (ViewBag.IsSuccess == true)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Congratulations</strong> You have added a new book successfully. <br />
            Click <a asp-controller="Book" asp-action="GetBook" asp-route-id="@ViewBag.BookId">here</a> to View the details
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }
    <div class="d-flex justify-content-center">
        <div class="spinner-border" role="status" id = "myLoader" style="display:none">
            <span class="sr-only">Loading...</span>
        </div>
    </div>

    <form method="post" enctype="multipart/form-data" data-ajax="false" asp-action="AddNewBook" asp-controller="Book" data-ajax-complete="myComplete"
          data-ajax-success="mySuccess" data-ajax-failure="myFailure" data-ajax-loading="#myLoader">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="LanguageId"></label>
            <select asp-for="LanguageId" class="form-control" asp-items="ViewBag.Language">
                <option value="">Please choose your languages</option>
            </select>
            <span asp-validation-for="LanguageId" class="text-danger"></span>
        </div>


        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Author"></label>
            <input asp-for="Author" class="form-control" />
            <span asp-validation-for="Author" class="text-danger"></span>
        </div>


        <div class="form-group">
            <label asp-for="Description"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description"></span>
        </div>

        <div class="form-group">
            <label asp-for="TotalPages"></label>
            <input asp-for="TotalPages" class="form-control" />
            <span asp-validation-for="TotalPages" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="CoverPhoto"></label>
            <div class="custom-file">
                <input asp-for="CoverPhoto" class="custom-file-input" id="customFile" />
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
            <span asp-validation-for="CoverPhoto" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="GalleryFiles"></label>
            <div class="custom-file">
                <input asp-for="GalleryFiles" class="custom-file-input" id="customFile" />
                <label class="custom-file-label" for="customFile">Choose files</label>
            </div>
            <span asp-validation-for="GalleryFiles" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="PdfFile"></label>
            <div class="custom-file">
                <input asp-for="PdfFile" class="custom-file-input" id="customFile" />
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
            <span asp-validation-for="PdfFile" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input type="submit" value="Add Book" class="btn btn-primary" />
        </div>



    </form>


</div>

@section scripts{ 
    <script>
        function myComplete(data) {
            alert("Here is the alert for myComplete");
        }
        function myFailure(data) {
            alert("Here is the alert for myFailure");
        }
        function mySuccess(data) {
            alert("Here is the alert for mySuccess");
        }
    </script>
}







Webgentle.Bookstore/Views/Book/GetAllBooks.cshtml
@model IEnumerable<BookModel>

@{
    var param = new Dictionary<string, string>()
    {
        {"Name","Vivek" },
        {"Author", "Vishal" },
        {"Brother", "Rahul" }
    };

}





<div class="container">
    <h3 class="display-4">All books</h3>
    <div class="row">

        @foreach (var book in Model)
        {
            <div class="col-md-4">
                <partial name="_bookThumbnail" model="@book"/>
            </div>
        }


    </div>
</div>

Webgentle.Bookstore/Views/Book/GetBook.cshtml


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    @for (int i = 0; i < Model.Gallery.Count; i++)
                    {
                        <li data-target="#carouselExampleIndicators" data-slide-to="@i" class="@(i==0 ? "active" : "")"></li>
                    }
                </ol>
                <div class="carousel-inner">
                    @for (int i = 0; i < Model.Gallery.Count; i++)
                    {
                        <div class="@(i==0 ? "carousel-item active" : "carousel-item")">
                            <img class="d-block w-100" src="@Model.Gallery[i].URL" alt="@Model.Gallery[i].Name">
                        </div>
                    }
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Title</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-primary">
                    <span class="label label-primary">By: </span>
                    <span class="monospaced">@Model.Author</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <a class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal">
                        Read Now
                    </a>
                </div>
            </div>

            <hr />

            <ul class="list-group">
                <li class="list-group-item"><span class="font-weight-bold">Category - </span> @Model.Category</li>
                <li class="list-group-item"><span class="font-weight-bold">Total Pages - </span>@Model.TotalPages</li>
                <li class="list-group-item"><span class="font-weight-bold">Language - </span>@Model.Language</li>
            </ul>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            @*<embed src="@Model.PdfUrl" class="w-100"/>*@
                              <iframe src="@Model.PdfUrl" class="w-100"></iframe>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

Webgentle.Bookstore/Views/Home/AboutUs.cshtml



@section breadcrumb{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Page 1</a></li>
            <li class="breadcrumb-item active" aria-current="page">AboutUs</li>
        </ol>
    </nav>

}
<h1> This is about us page!!</h1>





Webgentle.Bookstore/Views/Home/ContactUs.cshtml


@section breadcrumb{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Page 1</a></li>
            <li class="breadcrumb-item active" aria-current="page">ContactUs</li>
        </ol>
    </nav>

}
<h1>ContactUs</h1>


Webgentle.Bookstore/Views/Home/Index.cshtml
@section breadcrumb{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Page 1</a></li>
            <li class="breadcrumb-item active" aria-current="page">Index</li>
        </ol>
    </nav>

}

<section class="jumbotron text-center">
    <div class="container">
        <h1>
            Welcome to Book Store. 
        </h1>
        <p class="lead text-muted">
            Here is the Home Page for my Book Store Application. And i am designing my first responsive page for application.
            And it is going to be very exciting throught this journey.
        </p>

        <p>
            <a href="#" class="btn btn-primary ny-2">Search Books</a>
        </p>
    </div>
</section>


<div class="py-5 bg-light ">
    <div class="container">
        @*<h3 class="h3">Top Books</h3>*@
        <big>Top Books</big>

        @*@await Component.InvokeAsync("TopBooks", new { count = 4});*@
        <vc:top-books count="5"></vc:top-books>

        
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            //alert("Document is ready!!")
        })</script>
}


Webgentle.Bookstore/Views/Shared/Components/TopBooks/Default.cshtml
@model IEnumerable<BookModel>

<div class="row">
    
        @foreach (var book in Model)
        {<div class="col md-4">
            <partial name="_bookThumbnail" model="book" />
         </div>
        }
</div>

Webgentle.Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity=""
              crossorigin="anonymous"
              asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute">
              
    </environment>

    
    <link href="~/css/Site.css" rel="stylesheet" />
</head>
<body>
    <partial name="_header">

    @RenderSection("breadcrumb", required: false)

    <main role="main">
        @RenderBody()
    </main>

    

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/jquery-validate/jquery.validate.js"></script>
        <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/jquery-validate/jquery.validate.min.js"></script>
        <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
         <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
    </environment>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    @RenderSection("scripts", required: false)
</body>
</html>

Webgentle.Bookstore/Views/Shared/_bookThumbnail.cshtml
@model BookModel

<div class="card mb-4 shadow-sm">
    <img src="@(string.IsNullOrEmpty(Model.CoverImagePath) ? "/images/logo1.jpg" : Model.CoverImagePath)" class="img-thumbnail">
    <div class="card-body">
        <h3 class="card-title">@(String.IsNullOrEmpty(Model.Title) ? "No Title" : Model.Title)</h3>
        <p class="card-text">@(String.IsNullOrEmpty(Model.Description) ? "There is no description to show" : Model.Description)</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a asp-controller="book" asp-action="getbook" asp-route-Id="@Model.Id" btn btn-sm btn-outline-secondary">View details</a>
            </div>
            <small class="text-muted">@(string.IsNullOrEmpty(Model.Author) ? "NA" : Model.Author)</small>
        </div>
    </div>
</div>

Webgentle.Bookstore/Views/Shared/_header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="~/images/logo.jpg" width="30" height="30" asp-append-version="true" />
                Book Store
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav">
                </ul>
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Index"> Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="AboutUs">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="ContactUs">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Book" asp-action="GetAllBooks">All Books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Book" asp-action="AddNewBook">Add a new Book</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>